export const LANE_X = {
  left: -2.05,
  center: 0,
  right: 2.05,
} as const

export const KIDS_ENDLESS_CONFIG = {
  initialHearts: 3,
  maximumHearts: 3,
  damageInvincibleSeconds: 1.8,
  fallInvincibleSeconds: 2,
  rowsAhead: 14,
  rowsBehind: 4,
  rowSpacing: 7,
  minimumMergeRowGap: 3,
  maximumMergeRowGap: 6,
  mergeCooldownRows: 2,
  itemMinimumGapRows: 5,
  initialSpeed: 8.4,
  maximumSpeedMultiplier: 1.6,
  magnetDurationSeconds: 5,
  slowDurationSeconds: 4,
  giantDurationSeconds: 4,
  eventMinimumDistance: 300,
  eventMinimumGapRows: 15,
  eventMaximumGapRows: 30,
  themeDistance: 500,
  laneSwitchThreshold: 0.55,
  laneFollow: 12,
  damageSlowSeconds: 0.55,
  damageSpeedMultiplier: 0.62,
  hudUpdateSeconds: 0.1,
  pruneBehindDistance: 42,
} as const
