export const UI_TEXT = {
  stage: 'ステージ',
  dragToStart: '左右にドラッグしてスタート',
  mergeGuide: '同じ数字のボールと合体しよう',
  gameOver: 'ゲームオーバー',
  stageClear: 'ステージクリア',
  retry: 'もう一度',
  paused: '一時停止中',
  resume: '再開する',
  best: 'ベスト',
  time: 'タイム',
  reachedNumber: '到達した数字',
  clearTime: 'クリアタイム',
  bestNumber: 'ベスト数字',
  bestTime: 'ベストタイム',
  sound: 'サウンド',
  soundOn: 'オン',
  soundOff: 'オフ',
  pause: '一時停止',
} as const
